apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      volumes:
      - name: app
        emptyDir: {}
      containers:
      - name: command-demo-container
        image: 354481699343.dkr.ecr.us-east-1.amazonaws.com/eks-blue-green:latest3
        volumeMounts:
        - mountPath: /app/.next/cache/images
          name: app
        command: [ "/app/entrypoint.sh" ]
        args: ["./node_modules/next/dist/bin/next", "start"]
        ports:
          - containerPort: 3000
            name: http
      restartPolicy: Always