apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      volumes:
      - name: app
        emptyDir: {}
      containers:
      - name: command-demo-container
        image: jltr93/dockerquickstart:nextjsdocker
        # volumeMounts:
        # - mountPath: /app/.next/cache/images
        #   name: app
        # command: [ "/app/entrypoint.sh" ]
        # args: ["./node_modules/next/dist/bin/next", "start"]
        ports:
          - containerPort: 3000
            name: http
        env:
          - name: NEXT_PUBLIC_MESSAGE
            value: testesttestest
      restartPolicy: Always