apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nextjs
  type: LoadBalancer